[Appearance]
color_scheme_path=@XDG_CONFIG_HOME@/qt6ct/colors/noctalia.conf
custom_palette=true
icon_theme=breeze
standard_dialogs=gtk3
style=Fusion

[Fonts]
general=Lexend,11,-1,5,50,0,0,0,0,0
fixed=Maple Mono NF,11,-1,5,50,0,0,0,0,0

[Interface]
show_shortcuts_in_context_menus=true
